### ISSUE TITLE
Error with Mend and Recycle 

### ISSUE THREAD

**Issue by FladiCZ** [bustedbunny/RecycleThis#1]
Hi, I already reported it on Reddit, but here is a log for the problem. With MendAndRecycle mod (the most popular mod for recycling), I'm getting these errors. 

(I removed your mod and it works fine, so I know for sure it's these two mods making problems) 

> Claire started 10 jobs in one tick. newJob=Recycle (Job_16485217) A=Thing_ElectricTailoringBench1604305 jobGiver=RimWorld.JobGiver_Work jobList=(Recycle (Job_16485177) A=Thing_ElectricTailoringBench1604305) (Recycle (Job_16485181) A=Thing_ElectricTailoringBench1604305) (Recycle (Job_16485185) A=Thing_ElectricTailoringBench1604305) (Recycle (Job_16485189) A=Thing_ElectricTailoringBench1604305) (Recycle (Job_16485193) A=Thing_ElectricTailoringBench1604305) (Recycle (Job_16485197) A=Thing_ElectricTailoringBench1604305) (Recycle (Job_16485201) A=Thing_ElectricTailoringBench1604305) (Recycle (Job_16485205) A=Thing_ElectricTailoringBench1604305) (Recycle (Job_16485209) A=Thing_ElectricTailoringBench1604305) (Recycle (Job_16485213) A=Thing_ElectricTailoringBench1604305) (Recycle (Job_16485217) A=Thing_ElectricTailoringBench1604305) 
> UnityEngine.StackTraceUtility:ExtractStackTrace ()
> Verse.Log:Error (string)
> Verse.AI.JobUtility:TryStartErrorRecoverJob (Verse.Pawn,string,System.Exception,Verse.AI.JobDriver)
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
> Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
> Verse.AI.JobDriver:EndJobWith (Verse.AI.JobCondition)
> Verse.AI.JobDriver:CheckCurrentToilEndOrFail ()
> Verse.AI.JobDriver:TryActuallyStartNextToil ()
> Verse.AI.JobDriver:ReadyForNextToil ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
> Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
> Verse.AI.JobDriver:EndJobWith (Verse.AI.JobCondition)
> Verse.AI.JobDriver:CheckCurrentToilEndOrFail ()
> Verse.AI.JobDriver:TryActuallyStartNextToil ()
> Verse.AI.JobDriver:ReadyForNextToil ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
> Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
> Verse.AI.JobDriver:EndJobWith (Verse.AI.JobCondition)
> Verse.AI.JobDriver:CheckCurrentToilEndOrFail ()
> Verse.AI.JobDriver:TryActuallyStartNextToil ()
> Verse.AI.JobDriver:ReadyForNextToil ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
> Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
> Verse.AI.JobDriver:EndJobWith (Verse.AI.JobCondition)
> Verse.AI.JobDriver:CheckCurrentToilEndOrFail ()
> Verse.AI.JobDriver:TryActuallyStartNextToil ()
> Verse.AI.JobDriver:ReadyForNextToil ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
> Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
> Verse.AI.JobDriver:EndJobWith (Verse.AI.JobCondition)
> Verse.AI.JobDriver:CheckCurrentToilEndOrFail ()
> Verse.AI.JobDriver:TryActuallyStartNextToil ()
> Verse.AI.JobDriver:ReadyForNextToil ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
> Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
> Verse.AI.JobDriver:EndJobWith (Verse.AI.JobCondition)
> Verse.AI.JobDriver:CheckCurrentToilEndOrFail ()
> Verse.AI.JobDriver:TryActuallyStartNextToil ()
> Verse.AI.JobDriver:ReadyForNextToil ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
> Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
> Verse.AI.JobDriver:EndJobWith (Verse.AI.JobCondition)
> Verse.AI.JobDriver:CheckCurrentToilEndOrFail ()
> Verse.AI.JobDriver:TryActuallyStartNextToil ()
> Verse.AI.JobDriver:ReadyForNextToil ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
> Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
> Verse.AI.JobDriver:EndJobWith (Verse.AI.JobCondition)
> Verse.AI.JobDriver:CheckCurrentToilEndOrFail ()
> Verse.AI.JobDriver:TryActuallyStartNextToil ()
> Verse.AI.JobDriver:ReadyForNextToil ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
> Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
> Verse.AI.JobDriver:EndJobWith (Verse.AI.JobCondition)
> Verse.AI.JobDriver:CheckCurrentToilEndOrFail ()
> Verse.AI.JobDriver:TryActuallyStartNextToil ()
> Verse.AI.JobDriver:ReadyForNextToil ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
> Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
> Verse.AI.JobDriver:EndJobWith (Verse.AI.JobCondition)
> Verse.AI.JobDriver:CheckCurrentToilEndOrFail ()
> Verse.AI.JobDriver:TryActuallyStartNextToil ()
> Verse.AI.JobDriver:ReadyForNextToil ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
> Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
> (wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.JobTrackerTick_Patch0 (Verse.AI.Pawn_JobTracker)
> (wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
> Verse.TickList:Tick ()
> (wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch1 (Verse.TickManager)
> Verse.TickManager:TickManagerUpdate ()
> (wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch1 (Verse.Game)
> Verse.Root_Play:Update ()

**Comment by bustedbunny** [comment]
yes, I managed to reproduce the error. Let's see what I can do.

**Comment by bustedbunny** [comment]
Made an update fixing this issue. Now both these mods should work fine.
